"""Editorial seed used to generate the versioned PHAK learning bundle.

Copy is deliberately concise and original while technical claims remain tied to
the FAA source page shown in each citation.
"""

from __future__ import annotations


def mc(prompt, options, correct, explanation):
    return {
        "kind": "multipleChoice",
        "prompt": prompt,
        "options": options,
        "correctIndex": correct,
        "explanation": explanation,
    }


def numeric(prompt, value, tolerance, unit, explanation, accepted_formats=None):
    answer = {"value": value, "tolerance": tolerance, "unit": unit}
    if accepted_formats:
        answer["acceptedFormats"] = accepted_formats
    return {
        "kind": "numeric",
        "prompt": prompt,
        "answer": answer,
        "explanation": explanation,
    }


def matching(prompt, pairs, explanation):
    return {
        "kind": "matching",
        "prompt": prompt,
        "pairs": pairs,
        "explanation": explanation,
    }


def lesson(title, page, concept, explanation, worked_example, practice):
    return {
        "title": title,
        "page": page,
        "concept": concept,
        "explanation": explanation,
        "workedExample": worked_example,
        "practice": practice,
    }


SECTIONS = [
    {
        "number": 1,
        "summary": "Understand the FAA framework, pilot certification path, and training resources that organize safe civil flight.",
        "acsCodes": ["PA.I.A.K1", "PA.I.A.K2"],
        "lessons": [
            lesson(
                "How U.S. civil aviation is organized",
                "1-7 to 1-11",
                "The FAA promotes safe civil aviation by issuing and enforcing standards under Title 14 of the Code of Federal Regulations.",
                "Rules, guidance, and operating information serve different purposes. Regulations are legally binding; the Aeronautical Information Manual explains accepted procedures; advisory circulars describe guidance and acceptable methods without becoming regulations themselves.",
                "Before a training flight, a student may check 14 CFR for a legal requirement, the AIM for an operating procedure, and an advisory circular for deeper guidance. Treating all three as interchangeable could hide whether a statement is mandatory.",
                mc(
                    "Which source contains legally enforceable federal aviation rules?",
                    ["Advisory circulars", "Title 14 CFR", "The Pilot's Handbook", "A flight school's syllabus"],
                    1,
                    "Title 14 CFR contains federal aviation regulations; handbooks, the AIM, and advisory circulars provide supporting information and guidance.",
                ),
            ),
            lesson(
                "Certificates, ratings, and privileges",
                "1-14 to 1-18",
                "A pilot certificate establishes a level of qualification, while category, class, and type ratings identify the aircraft privileges attached to it.",
                "Eligibility, aeronautical knowledge, experience, and proficiency requirements vary by certificate. A certificate alone does not authorize every operation: pilots must also meet recency, medical, endorsement, aircraft-rating, and operating-rule requirements.",
                "A private pilot airplane certificate with an airplane single-engine land rating does not by itself authorize acting as pilot in command of a complex airplane. The pilot also needs the applicable training and logbook endorsement.",
                matching(
                    "Match each credential term to its role.",
                    [
                        ("Certificate", "Overall pilot qualification level"),
                        ("Category", "Broad family such as airplane"),
                        ("Class", "Subdivision such as single-engine land"),
                    ],
                    "Certificates define qualification level; category and class ratings narrow the kinds of aircraft for which privileges apply.",
                ),
            ),
            lesson(
                "Training and certification checks",
                "1-19 to 1-24",
                "Flight training combines knowledge instruction, flight proficiency, endorsements, and a practical test measured against Airman Certification Standards.",
                "A certificated flight instructor teaches, evaluates readiness, and provides required endorsements. An authorized evaluator conducts the practical test, which integrates knowledge, risk management, and skill rather than treating them as isolated subjects.",
                "When a learner can perform a maneuver but misses its hazards, the task is not yet ACS-ready. The instructor should connect the maneuver to its knowledge elements and risk controls before endorsing the applicant.",
                mc(
                    "What does an ACS task integrate?",
                    ["Only stick-and-rudder skill", "Knowledge, risk management, and skill", "Only regulations and weather", "Aircraft ownership and insurance"],
                    1,
                    "The ACS evaluates the knowledge, risk management, and flight-skill elements of each task together.",
                ),
            ),
        ],
        "quiz": [
            ("1-7", mc("Which publication is regulatory?", ["14 CFR", "AIM", "PHAK", "An advisory circular"], 0, "Title 14 CFR is regulatory; the other publications support learning and operations.")),
            ("1-14", matching("Match the FAA resource to its primary use.", [("14 CFR", "Binding rules"), ("AIM", "Operating procedures and information"), ("Advisory circular", "Nonregulatory guidance")], "Regulations impose requirements, while the AIM and advisory circulars explain procedures and guidance.")),
            ("1-22", mc("Who normally provides the endorsements that establish an applicant's readiness for a practical test?", ["An air traffic controller", "A certificated flight instructor", "An aircraft mechanic", "An airport manager"], 1, "A CFI provides required training endorsements; an authorized evaluator administers the practical test.")),
        ],
        "imageQuiz": (
            "1-2",
            "The FAA page contrasts early flapping-wing ideas with Cayley's glider. Which advance moved design toward the modern airplane?",
            ["Using fixed lifting wings with separate control and propulsion concepts", "Increasing the number of flapping joints", "Replacing air with a vacuum around the wing", "Eliminating aerodynamic surfaces"],
            0,
            "Cayley's work separated lift, propulsion, and control and used fixed wings, a foundation of modern heavier-than-air design.",
        ),
        "glossary": [
            ("14 CFR", "The codified federal regulations governing civil aviation in the United States.", "1-7"),
            ("CFI", "A certificated flight instructor authorized to provide flight training and endorsements within applicable privileges.", "1-20"),
            ("ACS", "Airman Certification Standards that integrate knowledge, risk management, and skill for certification tasks.", "1-22"),
        ],
    },
    {
        "number": 2,
        "summary": "Apply structured decision-making, risk assessment, and single-pilot resource management before and during flight.",
        "acsCodes": ["PA.I.H.K1", "PA.I.H.R1", "PA.I.H.R2"],
        "lessons": [
            lesson(
                "ADM is a continuous process",
                "2-1 to 2-5",
                "Aeronautical decision-making is a systematic process for selecting the safest practical course of action in a changing flight environment.",
                "Good ADM starts before engine start and continues through postflight. The pilot detects changes, estimates their significance, chooses an outcome, identifies actions, carries them out, and evaluates the result instead of defending the original plan.",
                "A lowering ceiling is not merely noted; the pilot compares it with personal and regulatory limits, selects a diversion or landing option, acts while choices remain, and checks whether conditions improve as expected.",
                mc("A pilot notices weather deteriorating faster than forecast. What is the best ADM response?", ["Continue until the weather becomes illegal", "Reassess options and act while margins remain", "Ignore the change because the briefing was legal", "Wait for ATC to make the decision"], 1, "ADM requires updating the plan as conditions change and acting before options narrow."),
            ),
            lesson(
                "Use PAVE to expose risk",
                "2-9 to 2-12",
                "PAVE organizes hazards into Pilot, Aircraft, enVironment, and External pressures so that no major risk domain is skipped.",
                "A checklist does not make a flight safe by itself. Each identified hazard needs a control, such as delaying, carrying more fuel, choosing a different runway, taking an instructor, or canceling. Multiple moderate hazards can combine into an unacceptable overall risk.",
                "A current pilot, legal airplane, marginal crosswind, and pressure to arrive for an event may look acceptable in isolation. PAVE reveals the interaction between environment and external pressure and supports an early no-go or alternate plan.",
                matching("Match each observation to its PAVE category.", [("Pilot", "Fatigue after a short night"), ("Aircraft", "Inoperative landing light"), ("Environment", "Low ceilings along the route"), ("External pressures", "A promised arrival time")], "PAVE separates personal, machine, operating-environment, and schedule/social hazards."),
            ),
            lesson(
                "Manage attitudes and workload",
                "2-13 to 2-20",
                "Single-pilot resource management uses all available people, equipment, information, and time while countering hazardous attitudes.",
                "The five classic attitudes are anti-authority, impulsivity, invulnerability, macho, and resignation. Their antidotes slow impulsive choices and restore disciplined risk control. Task management, automation management, and situational awareness protect mental capacity.",
                "If a reroute arrives during turbulence, the pilot can engage appropriate automation, ask ATC for delay or clarification, stabilize the aircraft, and then reprogram. Aviate, navigate, communicate remains the workload priority.",
                mc("Which thought best counters impulsivity?", ["Rules do not apply to me", "Do it quickly", "Not so fast - think first", "What is the use?"], 2, "The antidote to impulsivity is to slow down and think before acting."),
            ),
        ],
        "quiz": [
            ("2-2", mc("What makes ADM effective during flight?", ["Never changing the original plan", "Continuously evaluating results and new information", "Delegating all decisions to ATC", "Using intuition without a process"], 1, "ADM is iterative: detect, decide, act, and evaluate as the situation evolves.")),
            ("2-10", matching("Match the PAVE category.", [("Pilot", "Illness or fatigue"), ("Aircraft", "Fuel or equipment status"), ("Environment", "Weather and terrain"), ("External pressures", "Schedule pressure")], "PAVE is a comprehensive preflight and inflight risk scan.")),
            ("2-5", mc("Several individually manageable hazards occur together. What should the pilot do?", ["Consider their combined effect", "Score only the single worst hazard", "Ignore any hazard that is legal", "Assume experience cancels them"], 0, "Risk often compounds; the combined exposure can exceed a safe margin.")),
        ],
        "imageQuiz": (
            "2-10",
            "Using the illustrated PAVE checklist, where should pressure to reach a meeting on time be recorded?",
            ["Pilot", "Aircraft", "enVironment", "External pressures"],
            3,
            "A promised arrival or schedule goal is an external pressure that can distort otherwise sound decisions.",
        ),
        "glossary": [
            ("ADM", "A systematic mental process for choosing and evaluating a safe course of action in aviation.", "2-1"),
            ("PAVE", "A risk checklist covering Pilot, Aircraft, enVironment, and External pressures.", "2-10"),
            ("SRM", "Single-pilot resource management: effective use of all available resources by one pilot.", "2-13"),
        ],
    },
    {
        "number": 3,
        "summary": "Recognize major aircraft components, axes, structural methods, and loads that influence airworthiness.",
        "acsCodes": ["PA.I.G.K1", "PA.I.B.K1"],
        "lessons": [
            lesson(
                "Components work as a system",
                "3-1 to 3-5",
                "The fuselage, wings, empennage, landing gear, and powerplant each carry specific loads and together form the airplane.",
                "The fuselage supports occupants and connects major assemblies. Wings produce most lift. The empennage provides stabilizing and control surfaces. Landing gear absorbs ground loads, and the powerplant creates thrust while supporting electrical and other systems.",
                "During preflight, a loose fairing is not judged only by appearance. Its location near a control surface, structural attachment, or cooling path determines how it could affect the whole aircraft.",
                mc("Which assembly normally includes the horizontal and vertical stabilizers?", ["Powerplant", "Empennage", "Landing gear", "Wing strut"], 1, "The tail assembly, or empennage, contains stabilizing and control surfaces."),
            ),
            lesson(
                "Axes, motion, and center of gravity",
                "3-3 to 3-4",
                "An airplane rolls about its longitudinal axis, pitches about its lateral axis, and yaws about its vertical axis, all referenced to the center of gravity.",
                "The three axes intersect at the center of gravity. Ailerons primarily control roll, the elevator controls pitch, and the rudder controls yaw. Because motion is coupled, coordinated control inputs may be required rather than treating each axis in isolation.",
                "In a right turn, right aileron input initiates roll about the longitudinal axis while coordinated rudder counters adverse yaw about the vertical axis.",
                matching("Match each motion to its axis.", [("Roll", "Longitudinal axis"), ("Pitch", "Lateral axis"), ("Yaw", "Vertical axis")], "Roll-longitudinal, pitch-lateral, and yaw-vertical are the standard motion-axis pairings."),
            ),
            lesson(
                "Structure carries flight loads",
                "3-5 to 3-15",
                "Truss, monocoque, and semimonocoque structures distribute loads differently, but damage to a load path can reduce strength beyond the visible area.",
                "Truss construction relies on a framework of members. Monocoque construction relies heavily on stressed skin. Semimonocoque construction combines stressed skin with frames, bulkheads, and stringers and is common in modern airplanes.",
                "A small wrinkle near a riveted frame may signal transferred or excessive stress. A pilot should not press it flat or dismiss it; the aircraft needs evaluation under approved maintenance procedures.",
                mc("Why are stringers used in semimonocoque construction?", ["To replace all stressed skin", "To help carry and distribute longitudinal loads", "To generate engine thrust", "To control fuel flow"], 1, "Stringers reinforce the skin and help carry longitudinal structural loads."),
            ),
        ],
        "quiz": [
            ("3-4", mc("Which component primarily provides yaw control?", ["Aileron", "Elevator", "Rudder", "Flap"], 2, "The rudder controls yaw about the vertical axis.")),
            ("3-3", matching("Match the airplane motion.", [("Aileron input", "Roll"), ("Elevator input", "Pitch"), ("Rudder input", "Yaw")], "The primary controls correspond to roll, pitch, and yaw.")),
            ("3-7", mc("Which construction uses stressed skin plus internal frames and stringers?", ["Pure truss", "Semimonocoque", "Fabric-only", "Rotor mast"], 1, "Semimonocoque construction shares loads among skin and internal members.")),
        ],
        "imageQuiz": (
            "3-4",
            "In the airplane-components figure, which labeled assembly contains the elevator and rudder?",
            ["Empennage", "Powerplant", "Main landing gear", "Wing"],
            0,
            "The elevator and rudder are control surfaces on the empennage.",
        ),
        "glossary": [
            ("Fuselage", "The central aircraft structure that carries occupants or payload and joins major assemblies.", "3-4"),
            ("Empennage", "The tail assembly, normally including stabilizers, elevator, and rudder.", "3-4"),
            ("Semimonocoque", "A structure in which stressed skin, frames, bulkheads, and stringers share loads.", "3-7"),
        ],
    },
    {
        "number": 4,
        "summary": "Connect atmospheric properties and physical laws to pressure, airflow, lift, drag, and wingtip vortices.",
        "acsCodes": ["PA.I.F.K1", "PA.VII.B.K1"],
        "lessons": [
            lesson(
                "Atmosphere sets the operating medium",
                "4-2 to 4-4",
                "Air has mass, pressure, density, and viscosity; changes in temperature, pressure, and humidity change aircraft and engine performance.",
                "Standard sea-level conditions provide a common reference: 29.92 inches of mercury and 15 degrees Celsius. Pressure and density normally decrease with altitude, and warmer air is less dense than colder air at the same pressure.",
                "On a hot high-elevation day, fewer air molecules move through the wing and engine. Expect reduced lift, propeller efficiency, and engine power compared with standard conditions.",
                numeric("Enter standard sea-level pressure in inches of mercury.", 29.92, 0.01, "inHg", "The standard datum is 29.92 inHg.", ["29.92", "29.92 inHg"]),
            ),
            lesson(
                "Newton and pressure explain airflow effects",
                "4-4 to 4-7",
                "Lift is consistent with both pressure differences around an airfoil and the downward change in momentum of the airflow.",
                "Bernoulli's principle relates higher flow speed to lower static pressure along a streamline, while Newton's laws describe how deflecting air produces an equal and opposite force. Neither should be used as a one-sentence explanation that ignores angle of attack and circulation.",
                "As a wing redirects air downward, the air receives downward momentum and the wing receives an upward reaction. At the same time, the pressure field around the wing produces a net aerodynamic force.",
                matching("Match the principle to the observation.", [("Bernoulli", "Higher speed accompanies lower static pressure"), ("Newton's third law", "Air deflected down produces an upward reaction"), ("Continuity", "Flow speeds up through a smaller passage")], "These principles describe compatible parts of the same airflow behavior."),
            ),
            lesson(
                "Airfoils shape pressure and vortices",
                "4-7 to 4-10",
                "Airfoil shape and angle of attack establish a pressure distribution; the spanwise pressure difference also produces wingtip vortices and induced drag.",
                "The center of pressure can move as angle of attack changes. Near the tips, higher-pressure air beneath the wing curls toward lower pressure above it, creating trailing vortices that are strongest when the airplane is heavy, clean, and slow.",
                "Behind a departing heavy aircraft, a light airplane pilot stays above the heavy's flight path and lands beyond its touchdown point, avoiding the sinking, outward-moving vortices.",
                mc("When are wingtip vortices generally strongest?", ["Light, dirty, and fast", "Heavy, clean, and slow", "Light, clean, and parked", "Only during descent"], 1, "Heavy weight, clean configuration, and slow speed require high lift and produce strong vortices."),
            ),
        ],
        "quiz": [
            ("4-3", numeric("What is standard sea-level temperature in degrees Celsius?", 15, 0.5, "°C", "The standard sea-level temperature is 15 °C.", ["15", "15 C", "15°C"])),
            ("4-5", matching("Match each term.", [("Static pressure", "Ambient pressure exerted by the air"), ("Dynamic pressure", "Pressure associated with motion"), ("Density", "Mass per unit volume")], "These properties determine the aerodynamic environment.")),
            ("4-10", mc("What causes a wingtip vortex?", ["Fuel moving in the wing", "Spanwise flow from high pressure below toward low pressure above", "The magneto firing order", "Cabin ventilation"], 1, "The pressure differential drives spanwise flow around the tip and rolls into a vortex.")),
        ],
        "imageQuiz": (
            "4-7",
            "The FAA airfoil figure compares several profiles. What geometric feature distinguishes a cambered airfoil from a symmetric one?",
            ["Its mean camber line is curved", "It has no chord line", "Its lower surface must be flat", "It cannot create lift"],
            0,
            "A cambered airfoil has a curved mean camber line; a symmetric airfoil's mean camber line coincides with its chord line.",
        ),
        "glossary": [
            ("Static pressure", "The ambient pressure of air independent of its motion relative to the aircraft.", "4-4"),
            ("Camber", "The curvature of an airfoil represented by its mean camber line.", "4-7"),
            ("Wingtip vortex", "Rotating airflow trailing a lifting wing because of the pressure difference around its tips.", "4-10"),
        ],
    },
    {
        "number": 5,
        "summary": "Use the four forces, stability, load factor, and angle of attack to predict airplane behavior across the envelope.",
        "acsCodes": ["PA.VII.B.K1", "PA.VII.B.K2", "PA.I.F.K1"],
        "lessons": [
            lesson(
                "Balance the four forces",
                "5-1 to 5-8",
                "Lift, weight, thrust, and drag act continuously; steady flight occurs when forces are balanced along the flight path, not because any force disappears.",
                "In straight-and-level unaccelerated flight, lift equals weight and thrust equals drag. During a stabilized climb, lift may be less than weight because part of thrust acts upward along the inclined flight path.",
                "Adding power without retrimming changes the force balance and may change both airspeed and pitch. The pilot establishes the desired attitude and power, then trims after the airplane stabilizes.",
                mc("In unaccelerated straight-and-level flight, which relationship is correct?", ["Lift is greater than weight", "Thrust equals drag", "Drag is zero", "Weight equals thrust"], 1, "Forces balance: lift equals weight and thrust equals drag."),
            ),
            lesson(
                "Stability resists displacement",
                "5-20 to 5-34",
                "Static stability describes the initial tendency after displacement; dynamic stability describes motion over time as the airplane returns, diverges, or oscillates.",
                "Longitudinal stability depends strongly on center-of-gravity position and tail forces. Lateral stability is influenced by dihedral and sweep, while directional stability relies heavily on the vertical tail and keel effect.",
                "After a gust raises the nose, an airplane with positive static longitudinal stability initially tends back toward its trimmed angle. Whether the oscillations diminish describes its dynamic stability.",
                matching("Match the stability type to its axis.", [("Longitudinal", "Pitch"), ("Lateral", "Roll"), ("Directional", "Yaw")], "Longitudinal, lateral, and directional stability correspond to pitch, roll, and yaw."),
            ),
            lesson(
                "Stalls depend on angle of attack",
                "5-35 to 5-47",
                "A wing stalls when it exceeds its critical angle of attack, regardless of indicated airspeed, attitude, or aircraft weight.",
                "Banking while maintaining altitude increases load factor and the lift required, which raises stall speed. An accelerated stall can therefore occur at a higher airspeed than a one-G stall. Recovery requires reducing angle of attack first.",
                "A level 60-degree bank produces about 2 G. Because stall speed changes with the square root of load factor, an airplane that stalls at 50 knots at 1 G stalls near 71 knots at 2 G.",
                numeric("A level 60° bank produces approximately what load factor?", 2, 0.1, "G", "A coordinated level 60° bank has a load factor of about 2 G.", ["2", "2 G", "2.0"]),
            ),
        ],
        "quiz": [
            ("5-3", mc("What directly causes an aerodynamic stall?", ["Low airspeed alone", "Exceeding the critical angle of attack", "Retracting the landing gear", "A nose-low attitude"], 1, "A stall occurs when the critical angle of attack is exceeded.")),
            ("5-22", matching("Match stability with motion.", [("Longitudinal", "Pitch"), ("Lateral", "Roll"), ("Directional", "Yaw")], "The three stability axes map to pitch, roll, and yaw.")),
            ("5-38", numeric("If a 1-G stall speed is 50 knots, estimate the stall speed at 2 G using Vs(new)=Vs×√n.", 70.7, 1.0, "knots", "50 × √2 is approximately 70.7 knots.", ["70.7", "71", "71 knots"])),
        ],
        "imageQuiz": (
            "5-4",
            "On the coefficient graph, what happens after the wing passes the angle for maximum lift coefficient?",
            ["Lift coefficient decreases as the wing stalls", "Drag becomes zero", "Angle of attack resets to zero", "Weight disappears"],
            0,
            "Beyond the critical angle, separated flow grows and the lift coefficient decreases.",
        ),
        "glossary": [
            ("Angle of attack", "The angle between an airfoil's chord line and the relative wind.", "5-3"),
            ("Load factor", "The ratio of aerodynamic load supported by the wings to the aircraft's weight.", "5-38"),
            ("Critical angle of attack", "The angle of attack beyond which smooth airflow breaks down enough to cause a stall.", "5-41"),
        ],
    },
    {
        "number": 6,
        "summary": "Relate primary and secondary flight controls to axes, coordination, lift, drag, and trim.",
        "acsCodes": ["PA.I.G.K1", "PA.VII.A.K1"],
        "lessons": [
            lesson(
                "Primary controls command three axes",
                "6-1 to 6-4",
                "Ailerons control roll, the elevator or stabilator controls pitch, and the rudder controls yaw.",
                "Control effectiveness depends on airflow. At low airspeed, larger deflections may be needed for the same response; at high airspeed, abrupt inputs can create large structural loads. Control feel and system design vary by aircraft.",
                "During a slow-flight turn, the pilot coordinates aileron and rudder while managing pitch with the elevator, avoiding large or abrupt deflections near the stall.",
                matching("Match the control to its primary motion.", [("Aileron", "Roll"), ("Elevator", "Pitch"), ("Rudder", "Yaw")], "Aileron-roll, elevator-pitch, and rudder-yaw are the primary pairings."),
            ),
            lesson(
                "Coordinate and manage adverse yaw",
                "6-3 to 6-6",
                "Aileron deflection can create unequal drag that yaws the nose opposite the intended roll, called adverse yaw.",
                "The down-going aileron increases camber and lift but also drag. Differential or Frise ailerons reduce adverse yaw, while coordinated rudder counters what remains. The inclinometer helps the pilot detect slip or skid.",
                "To roll right, the left aileron moves down and can pull the nose left. Timely right rudder keeps the longitudinal axis aligned with the flight path.",
                mc("When rolling right, adverse yaw initially tends to move the nose which way?", ["Right", "Left", "Straight up", "Straight down"], 1, "The down-going left aileron adds drag, tending to yaw the nose left unless coordinated rudder is used."),
            ),
            lesson(
                "Secondary controls reshape workload",
                "6-6 to 6-12",
                "Flaps, leading-edge devices, spoilers, and trim systems change lift, drag, control force, or descent behavior.",
                "Flaps generally increase both lift and drag, allowing lower approach speed and steeper descent. Trim relieves sustained control pressure but does not hold altitude automatically. Spoilers reduce lift and increase drag.",
                "After configuring landing flaps and stabilizing on final, the pilot trims away steady elevator pressure while continuing to control airspeed and glidepath.",
                mc("What is trim primarily used to do?", ["Increase maximum structural load", "Relieve sustained control pressure", "Replace the elevator", "Guarantee altitude hold"], 1, "Trim balances control forces around a selected condition; the pilot remains responsible for the flight path."),
            ),
        ],
        "quiz": [
            ("6-3", mc("Which control primarily moves the airplane about the lateral axis?", ["Aileron", "Elevator", "Rudder", "Spoiler"], 1, "Pitch about the lateral axis is controlled primarily by the elevator or stabilator.")),
            ("6-3", matching("Match control and axis.", [("Aileron", "Longitudinal axis"), ("Elevator", "Lateral axis"), ("Rudder", "Vertical axis")], "The primary flight controls act mainly about these axes.")),
            ("6-7", mc("Extending flaps normally produces what combination?", ["Less lift and less drag", "More lift and more drag", "More thrust and less weight", "No aerodynamic change"], 1, "Flaps alter camber and often area, increasing lift and drag.")),
        ],
        "imageQuiz": (
            "6-3",
            "In the control-and-axes illustration, which surface initiates roll about the longitudinal axis?",
            ["Ailerons", "Elevator", "Rudder", "Flaps together"],
            0,
            "Differential aileron movement creates a rolling moment about the longitudinal axis.",
        ),
        "glossary": [
            ("Adverse yaw", "Yaw opposite the direction of roll caused largely by unequal aileron drag.", "6-4"),
            ("Trim", "A system used to relieve sustained pilot control pressure at a selected condition.", "6-8"),
            ("Flap", "A secondary wing surface used to increase lift and drag for low-speed operations.", "6-7"),
        ],
    },
    {
        "number": 7,
        "summary": "Operate piston-engine, propeller, fuel, electrical, environmental, and related aircraft systems within their limits.",
        "acsCodes": ["PA.I.G.K1", "PA.I.G.K2", "PA.IX.C.K1"],
        "lessons": [
            lesson(
                "Turn combustion into useful power",
                "7-1 to 7-8",
                "A four-stroke reciprocating engine repeats intake, compression, power, and exhaust while the propeller converts shaft power into thrust.",
                "The induction system meters air, the fuel system adds fuel, magnetos supply ignition independently of the main electrical system, and oil cools, cleans, seals, and lubricates. Instrument indications must be interpreted together rather than as isolated numbers.",
                "A rough engine with carburetor ice symptoms may improve after carburetor heat is selected, initially becoming rougher as ice melts. A falling oil-pressure indication paired with rising oil temperature demands prompt action under the checklist.",
                matching("Put each event with its four-stroke phase.", [("Intake", "Fuel-air charge enters"), ("Compression", "Charge is squeezed"), ("Power", "Ignited gases drive the piston"), ("Exhaust", "Burned gases leave")], "The cycle is intake, compression, power, and exhaust."),
            ),
            lesson(
                "Propeller and mixture choices change efficiency",
                "7-5 to 7-13",
                "A propeller blade is a rotating airfoil; blade angle, rotational speed, forward speed, air density, and engine power determine thrust.",
                "A fixed-pitch propeller is a compromise between climb and cruise. A constant-speed system varies blade angle to hold selected rpm. Mixture is adjusted as recommended to maintain efficient combustion as air density changes.",
                "In a climb with a constant-speed propeller, the governor changes blade angle to maintain selected rpm as aerodynamic load changes. The pilot still monitors manifold pressure, temperature, and limitations.",
                mc("What does a constant-speed propeller governor primarily maintain?", ["A selected engine rpm", "A fixed fuel quantity", "Cabin pressure", "A fixed groundspeed"], 0, "The governor varies blade angle to maintain the selected rpm within its operating range."),
            ),
            lesson(
                "Know the supporting systems",
                "7-14 to 7-42",
                "Fuel, electrical, hydraulic, pressurization, oxygen, and anti-ice systems have distinct failure indications and backup paths.",
                "An alternator normally supplies the electrical system and recharges the battery; the battery offers limited reserve. Fuel-system design determines venting, selector use, pumps, and unusable fuel. Pressurization and oxygen protect occupants from low ambient pressure but require specific emergency responses.",
                "An ammeter or loadmeter showing loss of alternator output prompts confirmation, load shedding, checklist use, and landing before the battery is exhausted rather than simply cycling switches repeatedly.",
                mc("After confirmed alternator failure, why should nonessential electrical loads be shed?", ["To make the propeller turn faster", "To extend limited battery endurance", "To increase fuel octane", "To pressurize the cabin"], 1, "Reducing electrical demand preserves the battery for essential equipment and landing."),
            ),
        ],
        "quiz": [
            ("7-3", mc("Which stroke produces useful force on the piston?", ["Intake", "Compression", "Power", "Exhaust"], 2, "Combustion during the power stroke forces the piston down.")),
            ("7-3", matching("Match each system component to its job.", [("Magneto", "Independent ignition energy"), ("Carburetor", "Meters fuel into induction air"), ("Oil system", "Lubricates and helps cool"), ("Alternator", "Supplies electrical power in normal operation")], "Each component supports combustion or aircraft services in a distinct way.")),
            ("7-21", mc("What can be an early indication of carburetor ice in a fixed-pitch airplane?", ["A gradual rpm loss", "An immediate oil quantity increase", "Higher battery voltage", "A brighter landing light"], 0, "Carburetor ice restricts airflow and commonly causes a gradual rpm loss with a fixed-pitch propeller.")),
        ],
        "imageQuiz": (
            "7-2",
            "Which engine arrangement shown on the FAA page is most common in many light training airplanes?",
            ["Horizontally opposed", "Radial only", "Inline steam", "Electric turbine"],
            0,
            "Air-cooled, horizontally opposed reciprocating engines are common in light airplanes.",
        ),
        "glossary": [
            ("Magneto", "An engine-driven ignition source that operates independently of the aircraft electrical system.", "7-4"),
            ("Carburetor ice", "Ice formed in a carburetor because of fuel vaporization and pressure-related cooling.", "7-20"),
            ("Constant-speed propeller", "A propeller system that changes blade angle to maintain selected rpm.", "7-9"),
        ],
    },
    {
        "number": 8,
        "summary": "Interpret pitot-static, gyroscopic, magnetic, and electronic instruments while recognizing their errors and failures.",
        "acsCodes": ["PA.VIII.A.K1", "PA.VIII.A.K2", "PA.I.G.K1"],
        "lessons": [
            lesson(
                "Pitot-static instruments compare pressure",
                "8-1 to 8-10",
                "The altimeter, vertical speed indicator, and airspeed indicator use static pressure; the airspeed indicator also uses pitot total pressure.",
                "A blocked pitot tube or static port affects instruments differently depending on whether drain paths remain open. Altimeter setting, nonstandard temperature, and pressure changes create errors that pilots must anticipate.",
                "If the static port is blocked, the altimeter freezes, the VSI reads zero, and the airspeed indicator becomes unreliable as altitude changes. An approved alternate-static source may restore usable indications with known errors.",
                matching("Match each instrument to the way it uses pressure.", [("Altimeter", "Static pressure acting on aneroid wafers"), ("VSI", "Static-pressure change through a calibrated leak"), ("Airspeed indicator", "Pitot-to-static pressure difference")], "The ASI compares pitot with static pressure, the altimeter senses pressure level, and the VSI senses its rate of change."),
            ),
            lesson(
                "Gyros and compasses have limits",
                "8-11 to 8-20",
                "Rigidity in space and precession support gyroscopic instruments, while the magnetic compass aligns with Earth's field and has turning and acceleration errors.",
                "The attitude and heading indicators depend on gyroscopic or solid-state references; the turn coordinator displays rate and roll trend. Vacuum, pressure, or electrical power-source failures can remove multiple instruments together.",
                "A vacuum-system failure can make both an attitude indicator and heading indicator slowly unreliable. Cross-checking the turn coordinator, compass, and performance instruments helps detect the common-source failure.",
                mc("Why can two gyroscopic instruments fail together?", ["They may share a power source", "All gyros use pitot pressure", "The compass controls them", "They share the fuel selector"], 0, "Common vacuum or electrical power can create a shared failure mode."),
            ),
            lesson(
                "Electronic displays still need cross-checks",
                "8-20 to 8-28",
                "A primary flight display integrates attitude, airspeed, altitude, vertical speed, and navigation, but sensors and software can still fail or mislead.",
                "The air-data computer and attitude-heading reference system replace many mechanical functions. Redundancy, reversionary modes, annunciations, and disciplined cross-checking remain essential; a bright display is not proof that its data are valid.",
                "If the airspeed tape disagrees with pitch, power, and standby indications, the pilot verifies the failure, uses reliable backup information, and follows the abnormal checklist rather than chasing the suspect tape.",
                mc("What is the best response to one implausible indication on a glass display?", ["Trust it because it is digital", "Cross-check independent instruments and aircraft performance", "Reset every circuit breaker", "Turn off all avionics"], 1, "Cross-checking independent sources helps identify the failed sensor or display."),
            ),
        ],
        "quiz": [
            ("8-2", mc("Which instrument uses both pitot and static pressure?", ["Altimeter", "Vertical speed indicator", "Airspeed indicator", "Magnetic compass"], 2, "The ASI measures the difference between pitot total pressure and static pressure.")),
            ("8-2", matching("Match each indication to the primary sensed quantity.", [("Altimeter", "Static pressure level"), ("VSI", "Rate of static-pressure change"), ("Airspeed indicator", "Pitot-static pressure difference")], "Each instrument converts pressure information into a different flight indication.")),
            ("8-3", numeric("What altimeter setting represents standard pressure?", 29.92, 0.01, "inHg", "Standard pressure is 29.92 inHg.", ["29.92", "29.92 inHg"])),
        ],
        "imageQuiz": (
            "8-2",
            "In the pitot-static diagram, which instrument is connected to both the pitot line and static line?",
            ["Airspeed indicator", "Altimeter", "Vertical speed indicator", "Magnetic compass"],
            0,
            "The airspeed indicator compares pitot pressure with static pressure.",
        ),
        "glossary": [
            ("Pitot pressure", "Total pressure sensed by a forward-facing pitot opening.", "8-2"),
            ("Static pressure", "Undisturbed ambient atmospheric pressure supplied to static instruments.", "8-2"),
            ("AHRS", "An attitude and heading reference system that supplies electronic attitude and directional data.", "8-22"),
        ],
    },
    {
        "number": 9,
        "summary": "Use the POH/AFM, limitations, placards, required aircraft documents, and maintenance records to establish legal operation.",
        "acsCodes": ["PA.I.B.K1", "PA.I.B.K2", "PA.I.F.K1"],
        "lessons": [
            lesson(
                "The approved manual governs the airplane",
                "9-1 to 9-5",
                "The approved AFM or POH supplies operating limitations, procedures, performance, and loading information specific to an aircraft model and, where marked, the individual airplane.",
                "Section numbering is standardized in many manuals. Limitations are mandatory, while normal and emergency procedures turn those limits into actions. Supplements modify the manual for installed optional equipment.",
                "Installing an approved GPS may add a supplement with new limitations and procedures. The pilot reviews that supplement as part of the operating limitations, not as optional marketing material.",
                mc("Where should a pilot look for mandatory operating limits?", ["POH/AFM limitations section and required placards", "A general aviation magazine", "A fuel receipt", "An airport directory only"], 0, "Approved limitations and required placards establish the airplane's operating boundaries."),
            ),
            lesson(
                "Required documents establish status",
                "9-5 to 9-9",
                "Airworthiness and registration certificates, operating limitations, and current weight-and-balance information must be available as required for operation.",
                "The airworthiness certificate remains effective only while the aircraft conforms to its type design and is in condition for safe operation. Registration identifies the aircraft but does not prove its mechanical condition.",
                "A current registration certificate cannot make an airplane airworthy when a required inspection is overdue. Legal operation depends on both documentation and actual condition.",
                matching("Match document to purpose.", [("Airworthiness certificate", "Shows approved airworthiness status"), ("Registration certificate", "Identifies registered ownership"), ("Operating limitations", "Defines approved operating boundaries"), ("Weight-and-balance data", "Supports loading determination")], "Each required document answers a different legal or operational question."),
            ),
            lesson(
                "Inspections and records prove compliance",
                "9-9 to 9-14",
                "Maintenance records show inspections, repairs, alterations, and airworthiness-directive compliance; pilots use them with a physical preflight to determine airworthiness.",
                "Annual and, when applicable, 100-hour inspections have different return-to-service rules. Other recurring requirements can include transponder, ELT, altimeter/static-system, and VOR checks depending on the operation.",
                "For a VFR rental flight, the pilot checks that applicable inspections are current and discrepancies resolved, then still conducts a preflight inspection. Paper compliance alone cannot reveal new damage.",
                mc("Does a completed annual inspection eliminate the need for a pilot preflight?", ["Yes, for 12 calendar months", "No, the pilot must assess current condition before flight", "Yes, if the tanks are full", "Only at towered airports"], 1, "Inspections document maintenance status; the pilot must still determine that the aircraft is safe for the proposed flight."),
            ),
        ],
        "quiz": [
            ("9-2", mc("Which POH/AFM material is mandatory?", ["Limitations", "The table of contents", "A manufacturer's advertisement", "A training-school note"], 0, "Approved limitations define mandatory operating boundaries.")),
            ("9-6", matching("Match the aircraft record or document.", [("Registration", "Registered aircraft identity"), ("Airworthiness certificate", "Approved status while conformity and condition continue"), ("Maintenance records", "Inspection and repair history"), ("POH/AFM", "Procedures, limitations, and performance")], "Together these sources establish identity, approval, condition history, and operating information.")),
            ("9-10", mc("Who is responsible for determining that an aircraft is in condition for safe flight before acting as PIC?", ["The pilot in command", "Only the last mechanic", "The airport manager", "The fuel provider"], 0, "The PIC must determine the aircraft is airworthy and safe for the intended operation.")),
        ],
        "imageQuiz": (
            "9-6",
            "The FAA page shows sample certificates. Which document identifies the aircraft's registered owner but does not by itself establish mechanical airworthiness?",
            ["Registration certificate", "Airworthiness certificate", "Weight-and-balance report", "Equipment list"],
            0,
            "Registration records aircraft ownership/registration; current conformity and safe condition are separate airworthiness questions.",
        ),
        "glossary": [
            ("AFM", "An FAA-approved aircraft flight manual containing limitations, procedures, and performance information.", "9-1"),
            ("Operating limitations", "Approved boundaries expressed through the AFM/POH, markings, and placards.", "9-2"),
            ("Airworthiness", "Conformity to approved type design plus condition for safe operation.", "9-7"),
        ],
    },
    {
        "number": 10,
        "summary": "Calculate moments and center of gravity, verify the loading envelope, and predict the effects of improper loading.",
        "acsCodes": ["PA.I.F.K2", "PA.I.F.R1"],
        "lessons": [
            lesson(
                "Weight and CG both matter",
                "10-1 to 10-5",
                "Maximum weight protects structural and performance margins, while center-of-gravity limits protect stability, control, and recoverability.",
                "An aft CG reduces longitudinal stability and can make stall recovery difficult. A forward CG increases stability but may require excessive elevator force and increases stall speed or takeoff distance. Lateral imbalance can also affect controllability.",
                "A loading plan below maximum gross weight can still be unsafe if baggage moves the CG aft of its limit; both total weight and CG must pass.",
                mc("Which is a typical effect of an excessively aft CG?", ["Greater longitudinal stability", "Reduced stability and more difficult stall recovery", "Lower cruise speed only", "Automatic load-factor protection"], 1, "An aft CG reduces the tail force and longitudinal stability, narrowing recovery margins."),
            ),
            lesson(
                "Moment turns loading into math",
                "10-5 to 10-8",
                "Moment equals weight multiplied by arm, and loaded center of gravity equals total moment divided by total weight.",
                "Arms are measured from the datum with the sign convention defined by the manufacturer. Moments may be divided by 100 or 1,000 in a loading form, so units and index scale must remain consistent.",
                "A 150-pound passenger at a 40-inch arm creates 6,000 pound-inches of moment. Moving the passenger aft increases moment and shifts the total CG aft without changing total weight.",
                numeric("What moment is produced by 150 lb at an arm of 40 in?", 6000, 1, "lb-in", "Moment = weight × arm = 150 × 40 = 6,000 lb-in.", ["6000", "6,000", "6000 lb-in"]),
            ),
            lesson(
                "Finish with the approved envelope",
                "10-7 to 10-12",
                "A completed loading calculation is acceptable only when total weight and the resulting CG or moment fall within the approved envelope for that weight.",
                "Loading graphs are interpolation tools; the final envelope check accounts for limits that may change with weight. Fuel burn can move CG, so departure, landing, and critical intermediate conditions may all need evaluation.",
                "A point just inside the takeoff envelope may move outside as fuel burns from a forward tank. The pilot calculates the expected landing condition instead of assuming lower weight is always safer.",
                mc("After plotting a loading point inside the envelope at takeoff, what else may require checking?", ["Only tire color", "The CG after expected fuel burn", "The airport restaurant hours", "The magnetic compass deviation card font"], 1, "Fuel burn changes weight and can shift CG, so later loading conditions may matter."),
            ),
        ],
        "quiz": [
            ("10-6", numeric("An item weighs 80 lb and is placed at a 50 in arm. What is its moment?", 4000, 1, "lb-in", "80 × 50 = 4,000 lb-in.", ["4000", "4,000", "4000 lb-in"])),
            ("10-3", matching("Match each loading term.", [("Datum", "Reference plane for arms"), ("Arm", "Distance from datum"), ("Moment", "Weight multiplied by arm"), ("CG", "Total moment divided by total weight")], "These definitions form the basis of every loading calculation.")),
            ("10-8", numeric("Total weight is 2,000 lb and total moment is 80,000 lb-in. What is the CG arm?", 40, 0.1, "in", "CG = 80,000 ÷ 2,000 = 40 inches.", ["40", "40 in", "40.0"])),
        ],
        "imageQuiz": (
            "10-8",
            "What does a loading point outside the FAA center-of-gravity envelope indicate?",
            ["The loading is outside approved weight/CG limits", "The calculation is automatically rounded into limits", "Only cruise power must be reduced", "The aircraft is legal if total weight is low"],
            0,
            "Both weight and CG must place the loading point inside the approved envelope.",
        ),
        "glossary": [
            ("Datum", "An imaginary vertical reference plane from which horizontal arms are measured.", "10-5"),
            ("Arm", "Horizontal distance from the datum to an item's center of gravity.", "10-5"),
            ("Moment", "The product of an item's weight and arm.", "10-6"),
        ],
    },
    {
        "number": 11,
        "summary": "Predict density-altitude, runway, climb, range, and landing performance using approved data and conservative interpolation.",
        "acsCodes": ["PA.I.F.K3", "PA.I.F.K4", "PA.I.F.R2"],
        "lessons": [
            lesson(
                "Density altitude predicts performance",
                "11-1 to 11-5",
                "Density altitude is pressure altitude corrected for nonstandard temperature and is a practical index of how the airplane performs.",
                "High temperature, high elevation, low pressure, and humidity reduce density. The result is less engine power, propeller thrust, and wing lift at a given true airspeed, producing longer takeoff roll and weaker climb.",
                "At a mountain airport on a hot afternoon, the airplane may accelerate sluggishly even though the altimeter indicates only field elevation. A density-altitude calculation reveals the performance altitude the aircraft effectively experiences.",
                numeric("Field elevation is 2,500 ft and altimeter setting is 29.42 inHg. Estimate pressure altitude using field elevation + (29.92-setting)×1,000.", 3000, 50, "ft", "29.92 - 29.42 = 0.50 inHg; 0.50 × 1,000 + 2,500 = 3,000 ft.", ["3000", "3,000", "3000 ft"]),
            ),
            lesson(
                "Read performance charts conservatively",
                "11-9 to 11-20",
                "Approved performance charts require the exact configuration, weight, altitude, temperature, wind, runway, and technique stated in their conditions and notes.",
                "Interpolate carefully and round toward the conservative result. A dry paved level-runway chart does not directly predict a wet grass upslope takeoff. Add every published correction rather than choosing the most favorable one.",
                "If a chart gives 1,200 feet over a 50-foot obstacle before a 15-percent grass correction, the corrected minimum is 1,380 feet. A prudent runway margin is then added for real-world variation.",
                numeric("A chart distance is 1,200 ft and the POH requires a 15% increase. What is the corrected distance?", 1380, 2, "ft", "1,200 × 1.15 = 1,380 ft.", ["1380", "1,380", "1380 ft"]),
            ),
            lesson(
                "Climb, range, and landing involve tradeoffs",
                "11-6 to 11-28",
                "Best angle of climb gains the most altitude per horizontal distance; best rate gains the most altitude per unit time, and both change with altitude.",
                "Wind changes groundspeed and therefore climb gradient, range, and time without changing the airplane's indicated climb performance. Weight, configuration, surface condition, slope, and braking action strongly influence landing distance.",
                "To clear a nearby obstacle, VX may be appropriate until clear; for efficient altitude gain afterward, transition to VY. The exact speeds come from the current POH and may vary with conditions.",
                matching("Match each performance speed.", [("VX", "Best angle of climb"), ("VY", "Best rate of climb"), ("Best glide", "Maximum distance in still air after power loss")], "VX optimizes altitude per distance, VY altitude per time, and best glide distance without power."),
            ),
        ],
        "quiz": [
            ("11-4", mc("Which conditions produce the highest density altitude?", ["Low, cold, high pressure", "High, hot, low pressure", "Sea level, cold, dry", "Low elevation at standard temperature"], 1, "High elevation, high temperature, and low pressure raise density altitude.")),
            ("11-7", matching("Match the performance measure.", [("VX", "Altitude gained per horizontal distance"), ("VY", "Altitude gained per unit time"), ("Climb gradient", "Altitude gain divided by ground distance")], "Wind affects ground distance and therefore gradient even when rate is unchanged.")),
            ("11-12", numeric("A POH takeoff distance is 1,000 ft and a required correction adds 20%. What corrected distance should be used before adding a safety margin?", 1200, 2, "ft", "1,000 × 1.20 = 1,200 ft.", ["1200", "1,200", "1200 ft"])),
        ],
        "imageQuiz": (
            "11-4",
            "On the density-altitude chart, moving to a higher temperature at the same pressure altitude produces what result?",
            ["Higher density altitude", "Lower density altitude", "No change", "Zero pressure altitude"],
            0,
            "Warmer air is less dense, so density altitude increases at a fixed pressure altitude.",
        ),
        "glossary": [
            ("Pressure altitude", "Altitude indicated when the altimeter is set to 29.92 inHg.", "11-3"),
            ("Density altitude", "Pressure altitude corrected for nonstandard temperature, used as a performance index.", "11-4"),
            ("VX", "The speed for best angle of climb under the stated conditions.", "11-7"),
        ],
    },
    {
        "number": 12,
        "summary": "Use atmospheric stability, moisture, fronts, clouds, thunderstorms, icing, and turbulence to anticipate aviation hazards.",
        "acsCodes": ["PA.I.C.K1", "PA.I.C.K3", "PA.I.C.R1"],
        "lessons": [
            lesson(
                "Pressure, heat, and moisture drive weather",
                "12-1 to 12-10",
                "Unequal heating creates pressure differences and circulation, while temperature and moisture determine density, visibility, clouds, and precipitation.",
                "Air flows in response to pressure-gradient force but is turned by Earth's rotation and modified by surface friction. Relative humidity rises as temperature approaches dewpoint even when water-vapor content does not change.",
                "After sunset, surface air cools toward its dewpoint. A small temperature-dewpoint spread with light wind can support radiation fog, especially in low-lying moist areas.",
                mc("What happens to relative humidity as air cools toward its dewpoint without losing moisture?", ["It generally increases", "It always becomes zero", "It is unrelated to temperature", "It becomes wind speed"], 0, "Cooling toward dewpoint raises relative humidity and may produce saturation."),
            ),
            lesson(
                "Stability shapes clouds and turbulence",
                "12-10 to 12-18",
                "Stable air resists vertical motion and favors layered clouds, smooth air, and widespread steady precipitation; unstable air favors vertical clouds, turbulence, and showery precipitation.",
                "Lifting can occur through convection, terrain, fronts, or convergence. Cloud bases form when rising air cools to saturation. Temperature-dewpoint spread offers a rough estimate of convective cloud-base height.",
                "With surface temperature 24 °C and dewpoint 14 °C, the 10-degree spread suggests a convective cloud base near 4,000 feet AGL using roughly 400 feet per degree Celsius.",
                numeric("Estimate convective cloud-base height AGL for 24 °C temperature and 14 °C dewpoint using 400 ft per °C of spread.", 4000, 200, "ft AGL", "The spread is 10 °C; 10 × 400 = about 4,000 ft AGL.", ["4000", "4,000", "4000 ft"]),
            ),
            lesson(
                "Recognize fronts, storms, and icing",
                "12-18 to 12-26",
                "Fronts organize wind shifts, pressure changes, clouds, precipitation, and turbulence; thunderstorms add severe turbulence, lightning, hail, icing, wind shear, and heavy precipitation.",
                "Every thunderstorm needs moisture, unstable air, and lift and progresses through cumulus, mature, and dissipating stages. Structural icing requires visible moisture and freezing temperatures at the aircraft surface; freezing rain can create especially rapid accumulation.",
                "A mature cell near a route is avoided by a wide margin rather than penetrated beneath its anvil. A pilot also considers outflow, gust fronts, and cells hidden in cloud or precipitation.",
                matching("Match thunderstorm stage to dominant airflow.", [("Cumulus", "Mostly updrafts"), ("Mature", "Updrafts and downdrafts"), ("Dissipating", "Mostly downdrafts")], "The mature stage contains both strong updrafts and downdrafts and the full range of hazards."),
            ),
        ],
        "quiz": [
            ("12-14", mc("Which cloud pattern most often indicates unstable air?", ["Tall cumulus with showery precipitation", "Uniform stratus with smooth air", "No vertical motion anywhere", "A temperature inversion alone"], 0, "Unstable air supports vertical development, turbulence, and showers.")),
            ("12-23", matching("Match weather feature and typical signal.", [("Warm front", "Widespread layered clouds ahead"), ("Cold front", "Narrower band with more abrupt change"), ("Occluded front", "Cold front overtakes a warm front")], "Front type helps anticipate the sequence and concentration of weather.")),
            ("12-14", numeric("Temperature is 20 °C and dewpoint is 15 °C. Estimate a convective cloud base using 400 ft per °C of spread.", 2000, 200, "ft AGL", "The 5 °C spread × 400 gives about 2,000 ft AGL.", ["2000", "2,000", "2000 ft"])),
        ],
        "imageQuiz": (
            "12-23",
            "In the thunderstorm life-cycle figure, which stage contains both updrafts and downdrafts?",
            ["Mature", "Cumulus only", "Dissipating only", "Pre-cumulus"],
            0,
            "Precipitation initiates downdrafts while updrafts persist, marking the mature stage.",
        ),
        "glossary": [
            ("Dewpoint", "The temperature to which air must cool at constant pressure to become saturated.", "12-12"),
            ("Atmospheric stability", "The atmosphere's tendency to resist or enhance vertical motion.", "12-14"),
            ("Freezing rain", "Supercooled liquid precipitation that can freeze rapidly on contact with an aircraft.", "12-25"),
        ],
    },
    {
        "number": 13,
        "summary": "Combine observations, forecasts, advisories, radar, and pilot reports into a complete weather picture and update it in flight.",
        "acsCodes": ["PA.I.C.K2", "PA.I.C.K4", "PA.I.C.R2"],
        "lessons": [
            lesson(
                "Build a briefing from multiple sources",
                "13-1 to 13-6",
                "No single weather product supplies the whole picture; a briefing combines current observations, forecasts, advisories, radar, pilot reports, and NOTAM-related constraints.",
                "A standard briefing supports a planned flight, an abbreviated briefing updates selected information, and an outlook briefing supports a flight six or more hours away. Automated tools are useful, but pilots remain responsible for interpreting the information and obtaining updates.",
                "The evening before a morning trip, a pilot uses an outlook briefing to identify major systems, then obtains a standard briefing near departure and checks updates en route.",
                mc("Which briefing is intended primarily for a flight more than six hours away?", ["Outlook briefing", "Abbreviated briefing", "Inflight emergency briefing", "Airport advisory"], 0, "An outlook briefing is used for planning when departure is at least six hours away."),
            ),
            lesson(
                "Decode observations and forecasts",
                "13-6 to 13-13",
                "METARs report observed airport weather, TAFs forecast terminal conditions, and PIREPs report conditions actually encountered aloft.",
                "Codes convey wind, visibility, weather, sky condition, temperature/dewpoint, and pressure compactly. Valid time and modifiers matter: a report can be correctly decoded but too old or too distant to describe the route.",
                "In `METAR KABC 121755Z 22012G20KT 5SM -RA BKN020`, winds are from 220 degrees at 12 knots gusting 20, visibility is five statute miles, light rain is present, and the ceiling is broken at 2,000 feet AGL.",
                matching("Match product to purpose.", [("METAR", "Routine surface observation"), ("TAF", "Terminal forecast"), ("PIREP", "Pilot-observed condition aloft")], "METARs observe, TAFs forecast terminal weather, and PIREPs add airborne observations."),
            ),
            lesson(
                "Use advisories and radar with limits",
                "13-13 to 13-24",
                "AIRMETs, SIGMETs, and convective SIGMETs highlight significant hazards, while radar estimates precipitation rather than directly measuring every aviation hazard.",
                "Radar age, beam geometry, attenuation, and product latency limit tactical use. A gap in returns can reflect attenuation rather than a safe corridor. PIREPs help validate cloud tops, icing, turbulence, and conditions between stations.",
                "A pilot sees a dark gap between intense cells on a delayed radar image. Instead of treating it as a passage, the pilot maintains wide separation, checks cell movement and product age, and uses updated weather and ATC support strategically.",
                mc("Why is a datalink radar image unsuitable for weaving between thunderstorms?", ["It may be delayed and does not provide a real-time tactical picture", "It shows only airport pavement", "It cannot show precipitation", "It is a legal clearance"], 0, "Latency and radar limitations make datalink imagery a strategic avoidance tool, not tactical storm penetration guidance."),
            ),
        ],
        "quiz": [
            ("13-7", mc("What does `BKN020` report?", ["Broken cloud layer at 2,000 ft AGL", "Visibility 20 miles", "Wind 020 degrees", "Barometer 20.00 inHg"], 0, "Cloud heights in METARs are hundreds of feet AGL: 020 means 2,000 feet.")),
            ("13-7", matching("Match aviation weather product and function.", [("METAR", "Observed surface weather"), ("TAF", "Forecast terminal weather"), ("PIREP", "Condition reported by a pilot"), ("Convective SIGMET", "Significant convective hazard advisory")], "Each product contributes a different time, place, or hazard perspective.")),
            ("13-4", mc("What is an abbreviated briefing best used for?", ["Updating selected information after an earlier briefing", "Replacing all preflight planning", "Obtaining aircraft maintenance approval", "Filing a registration change"], 0, "An abbreviated briefing updates or supplements information already obtained.")),
        ],
        "imageQuiz": (
            "13-7",
            "Using the FAA weather-code table, what descriptor does `SH` represent in a METAR?",
            ["Showers", "Shallow", "Snow hail", "Sea haze"],
            0,
            "In METAR coding, SH is the descriptor for showers.",
        ),
        "glossary": [
            ("METAR", "A coded routine observation of surface weather at an aerodrome.", "13-7"),
            ("TAF", "A coded forecast of weather expected in an airport terminal area.", "13-9"),
            ("PIREP", "A pilot report of weather conditions encountered in flight.", "13-8"),
        ],
    },
    {
        "number": 14,
        "summary": "Operate safely around runways and traffic patterns using markings, signs, lighting, communications, and wake-turbulence avoidance.",
        "acsCodes": ["PA.III.A.K1", "PA.III.B.K1", "PA.III.C.K1"],
        "lessons": [
            lesson(
                "Read the airport surface",
                "14-1 to 14-13",
                "Runway and taxiway markings, signs, and lights form a consistent language that separates movement areas and protects runway entrances.",
                "A red sign with white characters is mandatory instruction; a yellow sign with black characters provides direction; a black sign with yellow characters identifies the current location. Runway holding-position markings have solid and dashed yellow lines.",
                "Approaching a hold-short line from the solid-line side, the pilot stops before the marking unless cleared to cross or enter the runway. Reading back a runway crossing or hold-short instruction reduces ambiguity.",
                matching("Match sign appearance to meaning.", [("Red with white characters", "Mandatory instruction"), ("Yellow with black characters", "Direction"), ("Black with yellow characters", "Location")], "Color and layout distinguish mandatory, direction, and location signs."),
            ),
            lesson(
                "Fly a predictable traffic pattern",
                "14-13 to 14-22",
                "Standard traffic patterns organize arrivals and departures through upwind, crosswind, downwind, base, and final legs, normally using left turns unless indicated otherwise.",
                "Entries should integrate without disrupting established traffic. Wind indicators, segmented circles, markings, lighting, radio calls, and visual scanning work together; a radio does not replace seeing and avoiding.",
                "Arriving at a nontowered field, the pilot listens, observes the wind and traffic, announces position, and enters on the recommended 45-degree entry to downwind when practical.",
                mc("What is the standard traffic-pattern turn direction unless markings or published information indicate otherwise?", ["Left", "Right", "Alternating", "Toward the terminal"], 0, "Standard traffic patterns use left turns unless right traffic is designated."),
            ),
            lesson(
                "Prevent incursions and wake encounters",
                "14-23 to 14-40",
                "Sterile-cockpit discipline, progressive taxi instructions, diagram use, position awareness, and explicit clearances reduce runway-incursion risk.",
                "Wake vortices sink and move outward behind a generating aircraft. They are strongest behind heavy, clean, slow airplanes. Avoidance depends on the other aircraft's rotation or touchdown point and wind drift, not only elapsed time.",
                "Departing behind a larger airplane, a pilot rotates before its rotation point and stays above its path, adjusting for crosswind and accepting delay when safe spacing is uncertain.",
                mc("Where should a light airplane normally touch down behind a larger landing airplane?", ["Beyond the larger airplane's touchdown point", "Before its touchdown point", "Exactly on its touchdown point", "On the adjacent taxiway"], 0, "Touching down beyond the generator's touchdown point helps avoid sinking vortices."),
            ),
        ],
        "quiz": [
            ("14-10", mc("What does a red airport sign with white characters indicate?", ["Mandatory instruction", "Taxiway direction", "Current location", "Distance remaining"], 0, "Red and white is reserved for mandatory instruction signs such as runway holding positions.")),
            ("14-10", matching("Match airport marking or sign.", [("Solid/dashed hold lines", "Runway holding position"), ("Black sign with yellow characters", "Current location"), ("Yellow sign with black characters", "Direction or destination")], "Surface cues provide position, routing, and protected-boundary information.")),
            ("14-15", mc("At a nontowered airport, radio transmissions do what?", ["Support coordination but do not replace see-and-avoid", "Provide an ATC clearance", "Guarantee the runway is clear", "Remove right-of-way responsibilities"], 0, "Pilots coordinate on the CTAF while continuing visual collision avoidance.")),
        ],
        "imageQuiz": (
            "14-10",
            "The FAA page shows runway holding-position markings. From which side must a pilot stop before crossing without a clearance?",
            ["The side with two solid yellow lines", "The side with only dashed lines", "Either side is always unrestricted", "Only the grass side"],
            0,
            "When approaching from the solid-line side, stop unless authorized to cross; the dashed side marks leaving the protected runway area.",
        ),
        "glossary": [
            ("Movement area", "Airport surface area used for takeoff, landing, and taxiing, excluding ramps and other nonmovement areas.", "14-8"),
            ("CTAF", "Common traffic advisory frequency used to coordinate at airports without an operating control tower.", "14-15"),
            ("Runway incursion", "An incorrect presence of an aircraft, vehicle, or person on the protected area of a landing or takeoff surface.", "14-25"),
        ],
    },
    {
        "number": 15,
        "summary": "Identify controlled, uncontrolled, special-use, and other airspace along with entry, equipment, communication, and weather requirements.",
        "acsCodes": ["PA.I.E.K1", "PA.I.E.K2", "PA.I.E.R1"],
        "lessons": [
            lesson(
                "Controlled classes reflect traffic and service",
                "15-1 to 15-7",
                "Classes A through E are controlled airspace with different dimensions, entry rules, equipment, communication, and VFR weather minima; Class G is uncontrolled.",
                "Class B surrounds the busiest airports and requires an explicit clearance. Class C requires two-way communications before entry. Class D normally surrounds a towered airport and also requires two-way communications. Class E often begins at 700 or 1,200 feet AGL but can start at the surface.",
                "A pilot calling a Class C tower has established two-way communication when ATC responds with the aircraft call sign. A generic 'aircraft calling, standby' does not establish it.",
                matching("Match class to a defining feature.", [("Class A", "IFR operations only"), ("Class B", "Explicit ATC clearance before entry"), ("Class C", "Two-way communication before entry"), ("Class G", "Uncontrolled airspace")], "Each class has distinct operating requirements; charted boundaries determine where they apply."),
            ),
            lesson(
                "Weather minima preserve separation",
                "15-7 to 15-9",
                "Basic VFR weather minima vary by airspace, altitude, and day or night to give pilots time to see and avoid traffic emerging from cloud.",
                "The common Class E below 10,000 feet MSL minimum is three statute miles visibility and cloud clearance of 500 feet below, 1,000 feet above, and 2,000 feet horizontal. Rules differ in other airspace and at other altitudes.",
                "Cruising in Class E below 10,000 feet MSL with three miles visibility is not enough if the aircraft cannot also maintain the required cloud clearance.",
                mc("What is the common VFR visibility minimum in Class E below 10,000 ft MSL?", ["1 statute mile", "3 statute miles", "5 statute miles", "No minimum"], 1, "Class E below 10,000 feet MSL generally requires three statute miles visibility plus 500-below, 1,000-above, 2,000-horizontal cloud clearance."),
            ),
            lesson(
                "Special-use airspace changes the plan",
                "15-3 to 15-12",
                "Prohibited, restricted, warning, military operations, alert, and controlled firing areas differ in legal status and hazard.",
                "Prohibited areas bar flight absent permission. Restricted areas contain unusual, often invisible hazards and require authorization when active. MOAs separate or alert IFR traffic from military activity, but VFR pilots should obtain activity status and use caution.",
                "A direct course crosses an active restricted area. The pilot obtains authorization from the controlling agency or routes around; simply remaining VFR does not permit entry.",
                mc("May a VFR pilot enter an active restricted area without authorization?", ["Yes, if visibility exceeds five miles", "No", "Yes, below 3,000 ft AGL", "Only with landing lights on"], 1, "Active restricted airspace requires authorization from the controlling agency."),
            ),
        ],
        "quiz": [
            ("15-5", mc("What is required before entering Class B airspace?", ["An explicit ATC clearance", "Only monitoring the frequency", "A flight plan in all cases", "No communication"], 0, "Class B entry requires a specific ATC clearance.")),
            ("15-3", matching("Match airspace with its treatment.", [("Prohibited area", "Flight barred absent permission"), ("Restricted area", "Authorization required when active"), ("MOA", "Military training activity; use caution and obtain status"), ("Alert area", "High training or unusual aerial activity")], "The charted type indicates both legal restriction and operational hazard.")),
            ("15-8", mc("In Class E below 10,000 ft MSL, what is the usual horizontal cloud clearance for VFR?", ["500 ft", "1,000 ft", "2,000 ft", "One statute mile"], 2, "The common requirement is 500 below, 1,000 above, and 2,000 feet horizontal.")),
        ],
        "imageQuiz": (
            "15-2",
            "In the FAA airspace profile, which class begins at 18,000 feet MSL over the contiguous United States?",
            ["Class A", "Class B", "Class D", "Class G"],
            0,
            "Class A generally extends from 18,000 feet MSL through flight level 600 over the contiguous United States and Alaska, including specified offshore airspace.",
        ),
        "glossary": [
            ("Controlled airspace", "Airspace of defined dimensions within which ATC service is provided according to classification.", "15-1"),
            ("Restricted area", "Airspace containing unusual hazards where flight may be restricted during active periods.", "15-3"),
            ("Mode C veil", "Airspace generally within 30 NM of a Class B primary airport where altitude-reporting equipment is required, subject to exceptions.", "15-6"),
        ],
    },
    {
        "number": 16,
        "summary": "Plan and monitor VFR navigation with charts, pilotage, dead reckoning, wind correction, radio aids, and GPS.",
        "acsCodes": ["PA.VI.A.K1", "PA.VI.A.K2", "PA.I.D.K1"],
        "lessons": [
            lesson(
                "Charts turn geography into a route",
                "16-1 to 16-8",
                "Sectional charts depict airports, airspace, terrain, obstructions, navigation aids, frequencies, and other information needed for visual navigation.",
                "Latitude and longitude locate points; true course is measured from true north. Current chart editions and legends matter because airspace, frequencies, obstacles, and airport data change.",
                "A direct line between airports may cross high terrain or restricted airspace. The pilot uses the chart to select checkpoints, safe altitudes, alternates, and a route that preserves options.",
                mc("Why must a pilot use a current sectional chart?", ["Operational data and airspace can change", "Old charts show no latitude", "Only current charts have colors", "A chart is an ATC clearance"], 0, "Navigation and airspace information is revised; current data is essential to planning."),
            ),
            lesson(
                "Dead reckoning predicts time and fuel",
                "16-8 to 16-20",
                "Dead reckoning combines course, wind correction, heading, true airspeed, groundspeed, time, and fuel burn, then checks predictions against visual checkpoints.",
                "Apply variation to convert between true and magnetic direction and compass deviation for compass heading. Wind correction changes heading and groundspeed; it does not move the destination on the chart.",
                "A 120-NM leg at 120 knots groundspeed takes one hour. At 9 gallons per hour, planned cruise fuel is 9 gallons before adding start, taxi, climb, reserve, and contingency fuel.",
                numeric("A 120 NM leg is flown at 120 knots groundspeed. How many minutes will the leg take?", 60, 1, "minutes", "Time = distance ÷ groundspeed = 120 ÷ 120 = 1 hour, or 60 minutes.", ["60", "60 min", "1 hour"]),
            ),
            lesson(
                "Electronic navigation needs monitoring",
                "16-20 to 16-35",
                "VOR, distance information, and GPS can improve position awareness, but database currency, signal geometry, integrity, settings, and pilot input determine reliability.",
                "GPS direct-to guidance can lead through airspace, terrain, or weather unless the route is evaluated. VOR accuracy checks and receiver indications matter. Pilotage and dead reckoning provide independent cross-checks and failure resilience.",
                "When the moving map shows a position that conflicts with two unmistakable landmarks, the pilot cross-checks source selection, database, receiver status, and heading rather than following the magenta line automatically.",
                mc("What is the safest use of GPS direct-to guidance?", ["Evaluate the resulting route for terrain, airspace, weather, and fuel", "Assume it guarantees obstacle clearance", "Ignore database currency", "Stop monitoring position"], 0, "Electronic guidance supplies a course, not a complete risk assessment or clearance."),
            ),
        ],
        "quiz": [
            ("16-9", numeric("A 90 NM leg at 120 knots groundspeed takes how many minutes?", 45, 1, "minutes", "90 ÷ 120 = 0.75 hour = 45 minutes.", ["45", "45 min"])),
            ("16-10", matching("Match navigation quantity.", [("True course", "Direction of route measured from true north"), ("Wind correction angle", "Heading adjustment for crosswind"), ("Groundspeed", "Speed over Earth's surface"), ("ETA", "Predicted arrival time")], "These quantities connect the charted route to aircraft motion and time.")),
            ("16-10", numeric("A flight leg takes 2 hours at 8 gallons per hour. How much cruise fuel is required before reserves and other phases?", 16, 0.2, "gal", "Cruise fuel is time multiplied by burn rate: 2 × 8 = 16 gallons.", ["16", "16 gal", "16 gallons"])),
        ],
        "imageQuiz": (
            "16-2",
            "On the FAA sectional example, what should a pilot consult to decode an unfamiliar chart symbol?",
            ["The current chart legend", "The magnetic compass deviation card", "The aircraft registration", "The ELT battery label"],
            0,
            "The sectional legend is the authoritative key for chart symbols, colors, and aeronautical information.",
        ),
        "glossary": [
            ("Pilotage", "Navigation by reference to visible landmarks and their charted positions.", "16-8"),
            ("Dead reckoning", "Navigation by computing direction, time, speed, and distance from a known position.", "16-9"),
            ("Variation", "Angular difference between true north and magnetic north at a location.", "16-10"),
        ],
    },
    {
        "number": 17,
        "summary": "Recognize and mitigate hypoxia, trapped-gas effects, spatial disorientation, vision limits, stress, fatigue, and substance impairment.",
        "acsCodes": ["PA.I.H.K2", "PA.I.H.K3", "PA.I.H.R3"],
        "lessons": [
            lesson(
                "Protect oxygen and pressure physiology",
                "17-1 to 17-7",
                "Hypoxia deprives body tissues of adequate oxygen and may impair judgment before the pilot recognizes symptoms.",
                "Hypoxic, hypemic, stagnant, and histotoxic hypoxia have different causes. Altitude, smoking, carbon monoxide, poor circulation, alcohol, and some medications can reduce oxygen delivery or use. Supplemental oxygen and descent are key controls when altitude-related symptoms appear.",
                "A pilot develops headache, euphoria, and poor coordination at altitude. Because self-diagnosis is unreliable, the pilot uses oxygen, descends, and evaluates occupants rather than waiting for certainty.",
                matching("Match hypoxia type to cause.", [("Hypoxic", "Insufficient oxygen pressure"), ("Hypemic", "Blood cannot carry enough oxygen"), ("Stagnant", "Inadequate circulation"), ("Histotoxic", "Tissues cannot use delivered oxygen")], "The four categories describe failures of pressure, carrying capacity, circulation, or cellular use."),
            ),
            lesson(
                "Trust instruments over false sensations",
                "17-7 to 17-15",
                "The vestibular system can create powerful false sensations during acceleration or prolonged turns, especially without a visible horizon.",
                "The leans, Coriolis illusion, graveyard spiral, somatogravic illusion, and inversion illusion can provoke dangerous control inputs. Avoid abrupt head movements, maintain an instrument cross-check, and recover by reference to reliable flight instruments.",
                "After a prolonged unnoticed bank, leveling the wings can feel like a bank in the opposite direction. The pilot accepts the instrument indication and keeps the wings level instead of re-entering the turn to feel upright.",
                mc("During suspected spatial disorientation in instrument conditions, what should the pilot trust?", ["Reliable flight instruments", "The strongest body sensation", "Passenger balance", "Engine sound alone"], 0, "Body sensations can be false; a disciplined instrument cross-check provides the reliable attitude reference."),
            ),
            lesson(
                "Manage vision, stress, fatigue, and substances",
                "17-15 to 17-30",
                "Night vision needs time and protection, while fatigue, dehydration, stress, alcohol, medications, and carbon monoxide can degrade performance even when a pilot is technically legal.",
                "Scanning with slight off-center viewing helps at night because rods are concentrated away from the fovea. The IMSAFE checklist screens illness, medication, stress, alcohol, fatigue, and emotion/eating. Minimum alcohol rules are not a guarantee of fitness.",
                "A pilot eight hours past a drink but still hung over does not fly. Legal elapsed time does not remove dehydration, sleep loss, or impaired judgment.",
                matching("Match IMSAFE item to check.", [("Illness", "Symptoms that could impair flight"), ("Medication", "Side effects or contraindications"), ("Stress", "Mental workload outside the cockpit"), ("Fatigue", "Sleep and alertness deficit")], "IMSAFE is a personal fitness screen, not merely a regulatory checklist."),
            ),
        ],
        "quiz": [
            ("17-3", mc("Why is hypoxia especially dangerous to pilot decision-making?", ["It may impair judgment before symptoms are recognized", "It always causes immediate pain", "It improves night vision", "It only affects passengers"], 0, "Early judgment and self-awareness impairment can prevent a pilot from recognizing the need to act.")),
            ("17-4", matching("Match hypoxia category.", [("Hypoxic", "Low available oxygen pressure"), ("Hypemic", "Reduced oxygen-carrying capacity"), ("Stagnant", "Poor circulation"), ("Histotoxic", "Cells cannot use oxygen")], "Different mechanisms can produce similar performance impairment.")),
            ("17-10", mc("What is the recommended response to a vestibular illusion in cloud?", ["Rely on a disciplined instrument cross-check", "Turn toward the sensation", "Close the eyes and continue", "Descend without checking attitude"], 0, "Reliable instruments, not vestibular sensation, should guide control.")),
        ],
        "imageQuiz": (
            "17-7",
            "The graveyard-spiral figure shows altitude loss during a prolonged turn. What begins a safe recovery?",
            ["Recognize the bank on instruments and level the wings smoothly", "Pull back harder while remaining banked", "Trust the sensation of level flight", "Increase the bank to stop descent"],
            0,
            "Leveling the wings removes the turning load; then pitch and power can be adjusted without tightening the spiral.",
        ),
        "glossary": [
            ("Hypoxia", "A state in which body tissues receive or use inadequate oxygen.", "17-3"),
            ("Spatial disorientation", "A false perception of aircraft attitude, altitude, or motion relative to Earth.", "17-9"),
            ("IMSAFE", "A personal checklist for Illness, Medication, Stress, Alcohol, Fatigue, and Emotion/Eating.", "17-18"),
        ],
    },
]
