#!/usr/bin/env python3
"""Generate Metro's literal require registry from catalog image URIs."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "src" / "content" / "catalog.json"
OUTPUT = ROOT / "src" / "content" / "figure-assets.ts"


def main() -> None:
    catalog = json.loads(CATALOG.read_text())
    uris = sorted(
        {
            question["image"]["uri"]
            for module in catalog["modules"]
            for section in module["sections"]
            for question in section["quiz"]
            if question["type"] == "image"
        }
    )
    missing = [uri for uri in uris if not (ROOT / uri).exists()]
    if missing:
        raise FileNotFoundError(f"Missing figure assets: {', '.join(missing)}")
    lines = [
        "import type { ImageSource } from 'expo-image';",
        "",
        "// Generated by scripts/content/generate_figure_assets.py. Metro requires literal paths.",
        "export const FIGURE_ASSETS: Record<string, ImageSource> = {",
    ]
    for uri in uris:
        relative = "../../" + uri
        basename = Path(uri).name
        lines.append(f"  '{uri}': require('{relative}'),")
        lines.append(f"  './{uri}': require('{relative}'),")
        if uri.startswith("assets/phak/chapter-"):
            lines.append(f"  '{basename}': require('{relative}'),")
    lines.extend(["};", ""])
    OUTPUT.write_text("\n".join(lines))
    print(f"Registered {len(uris)} bundled figures.")


if __name__ == "__main__":
    main()
