"""Stable source metadata for FAA-H-8083-25C ingestion.

PDF page numbers are one-based physical pages in the FAA download. Handbook page
labels are the chapter-prefixed labels printed on each page.
"""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SOURCE_URL = (
    "https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/"
    "faa-h-8083-25c.pdf"
)
SOURCE_FILE = PROJECT_ROOT / "tmp" / "pdfs" / "faa-h-8083-25c.pdf"
SOURCE_SHA256 = "247929cace0ab56b376e683eba540cc4c8f39f199ab35414e8b604e24f395cb7"
SOURCE_TITLE = "Pilot's Handbook of Aeronautical Knowledge"
SOURCE_EDITION = "FAA-H-8083-25C (2023)"


CHAPTERS = [
    {
        "number": 1,
        "title": "Introduction to Flying",
        "pdf_start": 16,
        "pdf_end": 39,
        "page_start": "1-1",
        "page_end": "1-24",
        "figure_pdf_page": 17,
        "figure_label": "1-2",
        "figure_caption": "Early heavier-than-air flight concepts",
        "asset": "chapter-01-early-flight.jpg",
    },
    {
        "number": 2,
        "title": "Aeronautical Decision-Making",
        "pdf_start": 40,
        "pdf_end": 71,
        "page_start": "2-1",
        "page_end": "2-32",
        "figure_pdf_page": 49,
        "figure_label": "2-10",
        "figure_caption": "PAVE preflight risk checklist",
        "asset": "chapter-02-pave-checklist.jpg",
    },
    {
        "number": 3,
        "title": "Aircraft Construction",
        "pdf_start": 72,
        "pdf_end": 87,
        "page_start": "3-1",
        "page_end": "3-16",
        "figure_pdf_page": 75,
        "figure_label": "3-4",
        "figure_caption": "Airplane components and structural construction",
        "asset": "chapter-03-airplane-components.jpg",
    },
    {
        "number": 4,
        "title": "Principles of Flight",
        "pdf_start": 88,
        "pdf_end": 97,
        "page_start": "4-1",
        "page_end": "4-10",
        "figure_pdf_page": 94,
        "figure_label": "4-7",
        "figure_caption": "Airfoil sections and pressure behavior",
        "asset": "chapter-04-airfoil-principles.jpg",
    },
    {
        "number": 5,
        "title": "Aerodynamics of Flight",
        "pdf_start": 98,
        "pdf_end": 148,
        "page_start": "5-1",
        "page_end": "5-51",
        "figure_pdf_page": 101,
        "figure_label": "5-4",
        "figure_caption": "Angle of attack, lift, and drag relationships",
        "asset": "chapter-05-angle-of-attack.jpg",
    },
    {
        "number": 6,
        "title": "Flight Controls",
        "pdf_start": 149,
        "pdf_end": 160,
        "page_start": "6-1",
        "page_end": "6-12",
        "figure_pdf_page": 151,
        "figure_label": "6-3",
        "figure_caption": "Primary controls, movement, and axes",
        "asset": "chapter-06-primary-controls.jpg",
    },
    {
        "number": 7,
        "title": "Aircraft Systems",
        "pdf_start": 161,
        "pdf_end": 202,
        "page_start": "7-1",
        "page_end": "7-42",
        "figure_pdf_page": 162,
        "figure_label": "7-2",
        "figure_caption": "Common reciprocating engine arrangements",
        "asset": "chapter-07-engine-arrangements.jpg",
    },
    {
        "number": 8,
        "title": "Flight Instruments",
        "pdf_start": 203,
        "pdf_end": 230,
        "page_start": "8-1",
        "page_end": "8-28",
        "figure_pdf_page": 204,
        "figure_label": "8-2",
        "figure_caption": "Pitot-static system and instruments",
        "asset": "chapter-08-pitot-static.jpg",
    },
    {
        "number": 9,
        "title": "Flight Manuals and Other Documents",
        "pdf_start": 231,
        "pdf_end": 244,
        "page_start": "9-1",
        "page_end": "9-14",
        "figure_pdf_page": 236,
        "figure_label": "9-6",
        "figure_caption": "Aircraft registration documentation",
        "asset": "chapter-09-aircraft-documents.jpg",
    },
    {
        "number": 10,
        "title": "Weight and Balance",
        "pdf_start": 245,
        "pdf_end": 256,
        "page_start": "10-1",
        "page_end": "10-12",
        "figure_pdf_page": 252,
        "figure_label": "10-8",
        "figure_caption": "Loading graph and center-of-gravity envelope",
        "asset": "chapter-10-loading-envelope.jpg",
    },
    {
        "number": 11,
        "title": "Aircraft Performance",
        "pdf_start": 257,
        "pdf_end": 284,
        "page_start": "11-1",
        "page_end": "11-28",
        "figure_pdf_page": 260,
        "figure_label": "11-4",
        "figure_caption": "Density altitude chart",
        "asset": "chapter-11-density-altitude.jpg",
    },
    {
        "number": 12,
        "title": "Weather Theory",
        "pdf_start": 285,
        "pdf_end": 310,
        "page_start": "12-1",
        "page_end": "12-26",
        "figure_pdf_page": 307,
        "figure_label": "12-23",
        "figure_caption": "Thunderstorm life cycle and hazards",
        "asset": "chapter-12-thunderstorm-cycle.jpg",
    },
    {
        "number": 13,
        "title": "Aviation Weather Services",
        "pdf_start": 311,
        "pdf_end": 334,
        "page_start": "13-1",
        "page_end": "13-24",
        "figure_pdf_page": 317,
        "figure_label": "13-7",
        "figure_caption": "METAR and PIREP coding references",
        "asset": "chapter-13-weather-codes.jpg",
    },
    {
        "number": 14,
        "title": "Airport Operations",
        "pdf_start": 335,
        "pdf_end": 375,
        "page_start": "14-1",
        "page_end": "14-40",
        "figure_pdf_page": 344,
        "figure_label": "14-10",
        "figure_caption": "Airport signs and runway markings",
        "asset": "chapter-14-airport-signs.jpg",
    },
    {
        "number": 15,
        "title": "Airspace",
        "pdf_start": 376,
        "pdf_end": 387,
        "page_start": "15-1",
        "page_end": "15-12",
        "figure_pdf_page": 377,
        "figure_label": "15-2",
        "figure_caption": "National Airspace System profile",
        "asset": "chapter-15-airspace-profile.jpg",
    },
    {
        "number": 16,
        "title": "Navigation",
        "pdf_start": 388,
        "pdf_end": 422,
        "page_start": "16-1",
        "page_end": "16-35",
        "figure_pdf_page": 389,
        "figure_label": "16-2",
        "figure_caption": "Sectional chart and legend",
        "asset": "chapter-16-sectional-chart.jpg",
    },
    {
        "number": 17,
        "title": "Aeromedical Factors",
        "pdf_start": 423,
        "pdf_end": 452,
        "page_start": "17-1",
        "page_end": "17-30",
        "figure_pdf_page": 429,
        "figure_label": "17-7",
        "figure_caption": "Vestibular illusions and the graveyard spiral",
        "asset": "chapter-17-spatial-disorientation.jpg",
    },
]
