import {DocumentsIcon} from '@sanity/icons/Documents'
import {defineArrayMember, defineField, defineType} from 'sanity'

export const section = defineType({
  name: 'section',
  title: 'Section',
  type: 'document',
  icon: DocumentsIcon,
  groups: [
    {name: 'identity', title: 'Identity', default: true},
    {name: 'curriculum', title: 'Curriculum'},
    {name: 'sources', title: 'Sources'},
  ],
  fields: [
    defineField({
      name: 'stableId',
      title: 'Stable ID',
      type: 'string',
      group: 'identity',
      validation: (rule) =>
        rule.required().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, {name: 'kebab-case ID'}),
    }),
    defineField({
      name: 'module',
      title: 'Module',
      type: 'reference',
      weak: true,
      to: [{type: 'module'}],
      group: 'identity',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'identity',
      validation: (rule) => rule.required().min(3).max(140),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'identity',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'order',
      title: 'Order',
      type: 'number',
      group: 'identity',
      validation: (rule) => rule.required().integer().positive(),
    }),
    defineField({
      name: 'chapterNumber',
      title: 'PHAK chapter number',
      type: 'number',
      group: 'identity',
      validation: (rule) => rule.required().integer().positive(),
    }),
    defineField({
      name: 'chapterTitle',
      title: 'PHAK chapter title',
      type: 'string',
      group: 'identity',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'sourcePages',
      title: 'Printed source page range',
      type: 'string',
      group: 'identity',
      description: 'For example, 1-1–1-18.',
      validation: (rule) => rule.required().min(1).max(80),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'richText',
      group: 'curriculum',
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'learningObjectives',
      title: 'Learning objectives',
      type: 'array',
      group: 'curriculum',
      of: [defineArrayMember({type: 'string'})],
      validation: (rule) => rule.required().min(1).unique(),
    }),
    defineField({
      name: 'heroFigure',
      title: 'Hero figure',
      type: 'reference',
      weak: true,
      to: [{type: 'figure'}],
      group: 'curriculum',
    }),
    defineField({
      name: 'lessons',
      title: 'Ordered lessons',
      type: 'array',
      group: 'curriculum',
      of: [defineArrayMember({type: 'reference', weak: true, to: [{type: 'lesson'}]})],
      validation: (rule) => rule.required().min(1).unique(),
    }),
    defineField({
      name: 'quizQuestions',
      title: 'Section quiz questions',
      type: 'array',
      group: 'curriculum',
      of: [defineArrayMember({type: 'reference', weak: true, to: [{type: 'question'}]})],
      validation: (rule) => rule.required().min(1).unique(),
    }),
    defineField({
      name: 'glossaryTerms',
      title: 'Glossary terms',
      type: 'array',
      group: 'curriculum',
      of: [defineArrayMember({type: 'reference', weak: true, to: [{type: 'glossaryTerm'}]})],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'acsCodes',
      title: 'ACS coverage',
      type: 'array',
      group: 'curriculum',
      of: [
        defineArrayMember({
          type: 'reference',
          weak: true,
          to: [{type: 'acsCode'}],
          options: {disableNew: true},
        }),
      ],
      validation: (rule) => rule.required().min(1).unique(),
    }),
    defineField({
      name: 'estimatedMinutes',
      title: 'Estimated completion time (minutes)',
      type: 'number',
      group: 'curriculum',
      validation: (rule) => rule.required().integer().positive(),
    }),
    defineField({
      name: 'passingScore',
      title: 'Quiz passing score (%)',
      type: 'number',
      group: 'curriculum',
      initialValue: 80,
      validation: (rule) => rule.required().integer().min(0).max(100),
    }),
    defineField({
      name: 'citations',
      title: 'Source citations',
      type: 'array',
      group: 'sources',
      of: [defineArrayMember({type: 'sourceCitation'})],
      validation: (rule) => rule.required().min(1),
    }),
  ],
  orderings: [
    {title: 'Curriculum order', name: 'orderAsc', by: [{field: 'order', direction: 'asc'}]},
    {title: 'Title', name: 'titleAsc', by: [{field: 'title', direction: 'asc'}]},
  ],
  preview: {
    select: {title: 'title', order: 'order', module: 'module.title', media: 'heroFigure.image'},
    prepare({title, order, module: moduleTitle, media}) {
      return {title: `${order ?? '?'}. ${title ?? 'Untitled section'}`, subtitle: moduleTitle, media}
    },
  },
})
