import { fireEvent, render, waitFor } from '@testing-library/react-native';
import * as Linking from 'expo-linking';
import { ContentReport, CONTENT_REPORT_EMAIL } from '@/components/content-report';
import type { Lesson, Section, SourceCitation } from '@/lib/content/types';
import { LessonScreen } from '@/screens/lesson-screen';

jest.mock('expo-linking', () => ({
  openURL: jest.fn(() => Promise.resolve(true)),
}));

jest.mock('@/components/question-interaction', () => ({
  QuestionInteraction: () => null,
}));

const citation: SourceCitation = {
  handbook: 'Pilot Handbook',
  edition: '2026',
  chapter: '2',
  page: '2-4',
  url: 'https://www.faa.gov/example.pdf',
};

const lesson: Lesson = {
  id: 'lesson-1',
  title: 'Lift fundamentals',
  order: 1,
  estimatedMinutes: 4,
  concept: 'Lift acts perpendicular to relative wind.',
  explanation: 'Angle of attack changes the lift generated by an airfoil.',
  workedExample: 'Increasing angle of attack increases lift until the critical angle.',
  sourceCitation: citation,
  acsCodes: ['PA.I.F.K1'],
  practice: {
    id: 'question-1',
    type: 'multipleChoice',
    prompt: 'Which direction does lift act?',
    explanation: 'Lift is perpendicular to relative wind.',
    sourceCitation: citation,
    acsCodes: ['PA.I.F.K1'],
    options: ['Perpendicular to relative wind', 'Parallel to relative wind'],
    correctIndex: 0,
  },
};

const section: Section = {
  id: 'section-1',
  title: 'Aerodynamics',
  order: 1,
  summary: 'Lift and drag fundamentals.',
  sourcePages: '2-1–2-10',
  acsCodes: ['PA.I.F.K1'],
  lessons: [lesson],
  quiz: [lesson.practice],
};

describe('ContentReport', () => {
  beforeEach(() => {
    jest.mocked(Linking.openURL).mockClear();
  });

  it('sends a lesson report to the content report address with lesson context', async () => {
    const screen = await render(
      <ContentReport contentType="lesson" content={lesson} lessonPart="workedExample" />,
    );

    await fireEvent.press(screen.getByLabelText('Report a content issue with this lesson'));
    const detailsInput = screen.getByLabelText('Content issue details');
    expect(detailsInput.props.enterKeyHint).toBe('done');
    expect(detailsInput.props.submitBehavior).toBe('blurAndSubmit');
    expect(screen.getByLabelText('Dismiss keyboard')).toBeTruthy();

    await fireEvent.changeText(detailsInput, 'The example is unclear.');
    await fireEvent.press(screen.getByText('SEND REPORT'));

    await waitFor(() => expect(Linking.openURL).toHaveBeenCalledTimes(1));
    const url = jest.mocked(Linking.openURL).mock.calls[0][0];
    const decodedUrl = decodeURIComponent(url);

    expect(decodedUrl).toContain(`mailto:${CONTENT_REPORT_EMAIL}`);
    expect(decodedUrl).toContain('Preflight content report: lesson-1');
    expect(decodedUrl).toContain('Part: Worked example');
    expect(decodedUrl).toContain(lesson.workedExample);
  });

  it('appears on both lesson content stages', async () => {
    const screen = await render(
      <LessonScreen
        section={section}
        lesson={lesson}
        lessonIndex={0}
        onExit={jest.fn()}
        onComplete={jest.fn()}
      />,
    );

    expect(screen.getByLabelText('Report a content issue with this lesson')).toBeTruthy();

    await fireEvent.press(screen.getByText('SHOW ME HOW'));

    expect(screen.getByLabelText('Report a content issue with this lesson')).toBeTruthy();
  });
});
