import { fireEvent, render, waitFor } from '@testing-library/react-native';
import { Alert } from 'react-native';
import { ContentReport } from '@/components/content-report';
import type { Lesson, Section, SourceCitation } from '@/lib/content/types';
import { LessonScreen } from '@/screens/lesson-screen';

jest.mock('expo-crypto', () => ({
  randomUUID: () => '2fb1f5c0-2acc-4b88-a1a9-44ed3d4e4651',
}));

jest.mock('@/components/question-interaction', () => ({
  QuestionInteraction: () => null,
}));

const citation: SourceCitation = {
  handbook: 'Pilot Handbook',
  edition: '2026',
  chapter: '2',
  page: '2-4',
  url: 'https://www.faa.gov/example.pdf',
};

const lesson: Lesson = {
  id: 'lesson-1',
  title: 'Lift fundamentals',
  order: 1,
  estimatedMinutes: 4,
  concept: 'Lift acts perpendicular to relative wind.',
  explanation: 'Angle of attack changes the lift generated by an airfoil.',
  workedExample: 'Increasing angle of attack increases lift until the critical angle.',
  sourceCitation: citation,
  acsCodes: ['PA.I.F.K1'],
  practice: {
    id: 'question-1',
    type: 'multipleChoice',
    prompt: 'Which direction does lift act?',
    explanation: 'Lift is perpendicular to relative wind.',
    sourceCitation: citation,
    acsCodes: ['PA.I.F.K1'],
    options: ['Perpendicular to relative wind', 'Parallel to relative wind'],
    correctIndex: 0,
  },
};

const section: Section = {
  id: 'section-1',
  title: 'Aerodynamics',
  order: 1,
  summary: 'Lift and drag fundamentals.',
  sourcePages: '2-1–2-10',
  acsCodes: ['PA.I.F.K1'],
  lessons: [lesson],
  quiz: [lesson.practice],
};

describe('ContentReport', () => {
  const fetchMock = jest.fn() as jest.MockedFunction<typeof fetch>;
  let alertSpy: jest.SpyInstance;

  beforeEach(() => {
    fetchMock.mockReset();
    fetchMock.mockResolvedValue({ ok: true, status: 200 } as Response);
    globalThis.fetch = fetchMock;
    alertSpy = jest.spyOn(Alert, 'alert').mockImplementation(() => undefined);
  });

  afterEach(() => {
    alertSpy.mockRestore();
  });

  it('submits a lesson report to the in-app endpoint with lesson context', async () => {
    const screen = await render(
      <ContentReport contentType="lesson" content={lesson} lessonPart="workedExample" />,
    );

    await fireEvent.press(screen.getByLabelText('Report a content issue with this lesson'));
    const detailsInput = screen.getByLabelText('Content issue details');
    expect(detailsInput.props.enterKeyHint).toBe('done');
    expect(detailsInput.props.submitBehavior).toBe('blurAndSubmit');
    expect(screen.getByLabelText('Dismiss keyboard')).toBeTruthy();

    await fireEvent.changeText(detailsInput, 'The example is unclear.');
    await fireEvent.press(screen.getByText('SUBMIT REPORT'));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(1));
    expect(fetchMock).toHaveBeenCalledWith(
      '/api/content-reports',
      expect.objectContaining({
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      }),
    );
    const request = fetchMock.mock.calls[0][1];
    const payload = JSON.parse(String(request?.body));

    expect(payload).toEqual(
      expect.objectContaining({
        submissionId: '2fb1f5c0-2acc-4b88-a1a9-44ed3d4e4651',
        contentType: 'lesson',
        contentId: 'lesson-1',
        contentPart: 'workedExample',
        details: 'The example is unclear.',
        sourceLabel: 'Pilot Handbook · p. 2-4',
      }),
    );
    expect(payload.contentSnapshot).toContain('Part: Worked example');
    expect(payload.contentSnapshot).toContain(lesson.workedExample);
    await waitFor(() =>
      expect(alertSpy).toHaveBeenCalledWith(
        'Report submitted',
        'Thanks — your report is ready for review.',
      ),
    );
  });

  it('submits question context through the same endpoint', async () => {
    const screen = await render(<ContentReport contentType="question" content={lesson.practice} />);

    await fireEvent.press(screen.getByLabelText('Report a content issue with this question'));
    await fireEvent.changeText(
      screen.getByLabelText('Content issue details'),
      'The answer wording is ambiguous.',
    );
    await fireEvent.press(screen.getByText('SUBMIT REPORT'));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(1));
    const payload = JSON.parse(String(fetchMock.mock.calls[0][1]?.body));
    expect(payload).toEqual(
      expect.objectContaining({
        contentType: 'question',
        contentId: 'question-1',
        contentPart: 'question',
      }),
    );
    expect(payload.contentSnapshot).toContain(lesson.practice.prompt);
    expect(payload.contentSnapshot).toContain(lesson.practice.explanation);
  });

  it('requires details before submitting', async () => {
    const screen = await render(
      <ContentReport contentType="lesson" content={lesson} lessonPart="concept" />,
    );

    await fireEvent.press(screen.getByLabelText('Report a content issue with this lesson'));
    await fireEvent.press(screen.getByText('SUBMIT REPORT'));

    expect(screen.getByText('Tell us what looks wrong or confusing.')).toBeTruthy();
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it('keeps details available when submission fails', async () => {
    fetchMock.mockResolvedValue({ ok: false, status: 500 } as Response);
    const screen = await render(
      <ContentReport contentType="lesson" content={lesson} lessonPart="concept" />,
    );

    await fireEvent.press(screen.getByLabelText('Report a content issue with this lesson'));
    const detailsInput = screen.getByLabelText('Content issue details');
    await fireEvent.changeText(detailsInput, 'This explanation contradicts the source.');
    await fireEvent.press(screen.getByText('SUBMIT REPORT'));

    await waitFor(() =>
      expect(alertSpy).toHaveBeenCalledWith(
        'Unable to submit report',
        'Check your connection and try again. Your report details are still here.',
      ),
    );
    expect(screen.getByLabelText('Content issue details').props.value).toBe(
      'This explanation contradicts the source.',
    );

    fetchMock.mockResolvedValue({ ok: true, status: 200 } as Response);
    await fireEvent.press(screen.getByText('SUBMIT REPORT'));
    await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(2));

    const firstPayload = JSON.parse(String(fetchMock.mock.calls[0][1]?.body));
    const retryPayload = JSON.parse(String(fetchMock.mock.calls[1][1]?.body));
    expect(retryPayload.submissionId).toBe(firstPayload.submissionId);
  });

  it('appears on both lesson content stages', async () => {
    const screen = await render(
      <LessonScreen
        section={section}
        lesson={lesson}
        lessonIndex={0}
        onExit={jest.fn()}
        onComplete={jest.fn()}
      />,
    );

    expect(screen.getByLabelText('Report a content issue with this lesson')).toBeTruthy();

    await fireEvent.press(screen.getByText('SHOW ME HOW'));

    expect(screen.getByLabelText('Report a content issue with this lesson')).toBeTruthy();
  });
});
